# Generated by Django 3.2.5 on 2023-09-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='script_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
